"use client";
import { useEffect, useRef, useState, type FormEvent, type CSSProperties } from "react";
import { Asterisk, Check, Clock3, CreditCard, Hand, MapPin, Menu, Play, Plus, QrCode, Search, ShieldCheck, Smartphone, Sparkles, X, Zap } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Checkbox } from "@/components/ui/checkbox";
import { machineLocations } from "@/lib/locations";

const categories = ["All designs", "Cat Eye", "Minimal", "Chrome", "Custom Photo", "Floral", "Party", "Seasonal"];
const designs = [
 { name:"Blue hour",category:"Cat Eye",note:"A little shimmer. A lot of blue.",tile:0 },
 { name:"Cherry picked",category:"Minimal",note:"A tiny detail with main-character energy.",tile:1 },
 { name:"Liquid silver",category:"Chrome",note:"A metallic-look moment.",tile:2 },
 { name:"Your favourite face",category:"Custom Photo",note:"Your camera roll, reimagined.",tile:3 },
 { name:"Freshly picked",category:"Floral",note:"Little blooms. Big mood.",tile:4 },
 { name:"Off the grid",category:"Party",note:"Checks that refuse to blend in.",tile:5 },
 { name:"Make it festive",category:"Seasonal",note:"A new look for your next occasion.",tile:6 },
 { name:"In the flow",category:"Minimal",note:"Clean lines. Your kind of minimal.",tile:7 },
];
const nav = [["How It Works","#how-it-works"],["Nail Designs","#nail-designs"],["Locations","#locations"],["For Venues","#for-venues"],["FAQs","#faqs"]];
const faqs = [
 {q:"What should I do before I arrive?",a:"Bring clean, dry nails and wash and dry your hands. Remove old polish and avoid hand cream, oil and residue on the nail surface. Follow the machine’s base-coat and preparation instructions for your nail type before printing."},
 {q:"Can I print on the nails I already have?",a:"The machine can print on natural nails, gel, shellac, acrylic, builder gel and press-on tips. Each nail is mapped before printing. Follow the preparation instructions on the touchscreen; the finish depends on the surface, preparation and design."},
 {q:"Can every finger have a different design?",a:"Yes. Choose a different design for each finger or use one design across your set. To print a personal photo, scan the QR code on the machine and upload from your phone. Only upload images you have permission to use."},
 {q:"How long does it take, and how much does it cost?",a:"Allow around six minutes for the printing experience. Preparation and drying time can vary. Check the price shown on the machine before you pay. Cash, card and contactless are accepted; no booking or app is needed."},
 {q:"Is there an age requirement?",a:"Anyone under 16 must be accompanied and supervised by a parent or guardian for the whole session. Children must not be left alone at a machine. Follow the venue’s rules as well as the on-screen instructions."},
 {q:"How do I keep the experience hygienic?",a:"Wash and dry your hands, then wipe the finger rest with the provided cleaning wipes before and after your session. Do not use the machine if you have a nail infection, broken or bleeding skin around the nail, or a known allergy to the nail products. Ask a qualified professional if you are unsure."},
 {q:"What affects the printed result?",a:"Nail shape, the underlying colour, preparation, your chosen image and movement during printing can affect the result. Keep your finger still and let the top coat set. Gallery images are design inspiration; they are not a guarantee of an identical finish."},
 {q:"What if the machine takes payment but does not print?",a:"Email jollynailprinting@gmail.com with the machine location, date, time and payment details so Jolly can arrange a refund or reprint for a machine failure. Change-of-mind and preparation issues are assessed under the published machine rules. Your rights under Australian Consumer Law are not limited."},
 {q:"How do I remove the design?",a:"For a printed finish on natural nails, use ordinary nail polish remover and follow the product instructions. For gel, shellac, acrylic or builder gel, ask your usual nail technician about suitable removal for the underlying product. Do not peel or force the coating off."},
 {q:"Where can I find a nail printer near me?",a:"Australian launch locations are coming soon. No venue addresses or opening dates are confirmed on this website yet. The location finder will show the centre, level, opening hours, map link and machine status when details are confirmed."},
];
const surfaces = ["Natural nails","Gel","Shellac","Acrylic","Builder gel","Press-on tips"];
const venueTypes = ["Shopping centre","Beauty venue / salon","Entertainment venue","Retail landlord","Hotel / gym","Other venue"];
function NailImage({tile,name,className=""}:{tile:number;name:string;className?:string}) {
 return <div className={"nail-image "+className} role="img" aria-label={name} style={{"--tile-x":(tile%4)*100/3+"%","--tile-y":tile<4?"0%":"100%"} as CSSProperties}/>;
}
export default function Home(){
 const [menuOpen,setMenuOpen]=useState(false),[videoOpen,setVideoOpen]=useState(false),[activeCategory,setActiveCategory]=useState("All designs"),[showAll,setShowAll]=useState(false);
 const [selectedDesign,setSelectedDesign]=useState<(typeof designs)[number]|null>(null);
 const [locationInput,setLocationInput]=useState(""),[searchedLocation,setSearchedLocation]=useState("");
 const [venueType,setVenueType]=useState(""),[consent,setConsent]=useState(false),[formStatus,setFormStatus]=useState<"idle"|"sending"|"success"|"error">("idle"),[formMessage,setFormMessage]=useState(""),[reference,setReference]=useState("");
 const submissionId=useRef("");
 const filtered=designs.filter(d=>activeCategory==="All designs"||d.category===activeCategory);
 const visibleDesigns=activeCategory==="All designs"&&!showAll?filtered.slice(0,4):filtered;
 const matchingLocations=machineLocations.filter(location=>!searchedLocation||[location.centreName,location.suburb,location.city,location.postcode].some(value=>value.toLowerCase().includes(searchedLocation.toLowerCase())));
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>void}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{context.registerTool({
   name:"filter_nail_designs",title:"Filter nail inspiration",description:"Show a category in the visible nail-design inspiration gallery. This does not order or reserve a design.",
   inputSchema:{type:"object",properties:{category:{type:"string",enum:categories}},required:["category"],additionalProperties:false},
   annotations:{readOnlyHint:false,untrustedContentHint:false},
   execute:(input:unknown)=>{const value=input as {category?:string};if(!value||!categories.includes(value.category||""))throw new Error("Choose a listed nail-design category.");setActiveCategory(value.category!);setShowAll(true);document.getElementById("nail-designs")?.scrollIntoView({behavior:"auto"});return new Promise(resolve=>requestAnimationFrame(()=>resolve({category:value.category,designs:designs.filter(d=>value.category==="All designs"||d.category===value.category).map(d=>d.name)})));},
  },{signal:lifecycle.signal});}catch{/* Visible controls work in browsers without WebMCP. */}
  return()=>lifecycle.abort();
 },[]);
 async function submitVenue(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(formStatus==="sending")return;
  if(!venueType||!consent){setFormStatus("error");setFormMessage("Choose your venue type and allow Jolly to contact you about this enquiry.");return;}
  const data=new FormData(event.currentTarget);if(!submissionId.current)submissionId.current=crypto.randomUUID();
  setFormStatus("sending");setFormMessage("");
  try{const response=await fetch("/api/venue-enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),organisation:data.get("organisation"),email:data.get("email"),phone:data.get("phone"),venueType,city:data.get("city"),message:data.get("message"),website:data.get("website"),consent,submissionId:submissionId.current})});
   const result=await response.json() as {error?:string;reference:string};if(!response.ok)throw new Error(result.error||"We couldn’t save your enquiry. Please try again or email Jolly.");setReference(result.reference);setFormStatus("success");
  }catch(error){setFormStatus("error");setFormMessage(error instanceof Error?error.message:"Please try again or email Jolly.");}
 }
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="site-header"><div className="nav-shell">
   <a href="#" className="wordmark" aria-label="Jolly Nail Printing home">jolly<span className="wordmark-dot">.</span><span className="wordmark-caption">NAIL PRINTING</span></a>
   <nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,href])=><a key={href} href={href}>{label}</a>)}</nav>
   <div className="header-actions"><a className="button button-blue nav-cta" href="#locations">Find a Jolly Machine</a><button className="menu-button" aria-label={menuOpen?"Close menu":"Open menu"} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div>
  </div>{menuOpen&&<nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation">{nav.map(([label,href])=><a key={href} href={href} onClick={()=>setMenuOpen(false)}>{label}</a>)}<a href="#venue-enquiry" onClick={()=>setMenuOpen(false)}>Host a Machine</a></nav>}</header>
  <main id="main">
   <section className="hero section-shell">
    <div className="hero-copy"><span className="eyebrow"><Asterisk size={18}/> A NEW WAY TO NAIL IT</span><h1>Nail art,<br/><span className="editorial-serif">printed</span> while<br/>you shop<span className="red-dot">.</span></h1><p>Your next look is a touchscreen away. Choose it. Make it yours. Print personalised nail art in minutes — no appointment needed.</p><div className="hero-actions"><a className="button button-blue" href="#locations"><MapPin size={18}/>Find a Jolly Machine</a><a className="button button-outline" href="#venue-enquiry">Host a Machine</a></div><div className="hero-launch"><span className="launch-line"/>COMING SOON TO AUSTRALIA</div></div>
    <div className="hero-visual"><div className="hero-photo"><img src="/images/jolly-hero.webp" alt="Glossy cobalt, cherry and patterned nail-art inspiration on a hand" width="1536" height="1024" fetchPriority="high"/><span className="hero-photo-label">SMALL CANVAS.<br/>BIG PERSONALITY.</span></div><span className="hero-sticker"><span>YOUR NAILS</span><Asterisk size={35}/><span>YOUR WAY</span></span><button className="machine-mini" onClick={()=>setVideoOpen(true)} aria-label="Watch the Jolly machine demonstration"><img src="/images/jolly-machine.webp" alt="Jolly nail printing machine preview" width="180" height="180"/><span className="machine-mini-copy"><span>BEAUTY, MEET TECH.</span><strong>See Jolly in action</strong><span className="play-label"><Play size={14} fill="currentColor"/> Watch the machine</span></span></button><span className="visual-index">01 / THE EVERYDAY UPGRADE</span></div>
   </section>
   <div className="trust-bar section-shell" aria-label="At a glance"><div><Clock3/><span><strong>Around 6 minutes</strong><small>Make a moment of it</small></span></div><div><Zap/><span><strong>No booking needed</strong><small>Walk up. Try it.</small></span></div><div><Sparkles/><span><strong>100+ designs</strong><small>Mix it up, finger by finger</small></span></div><div><CreditCard/><span><strong>Cash, card & contactless</strong><small>Pay at the machine</small></span></div></div>
   <div className="brand-ribbon" aria-hidden="true"><div>PRINT YOUR PERSONALITY <Asterisk/> A LITTLE ART. A LOT OF YOU. <Asterisk/> PRINT YOUR PERSONALITY <Asterisk/> A LITTLE ART. A LOT OF YOU. <Asterisk/></div></div>
   <section id="how-it-works" className="how-section section-shell section-space">
    <div className="section-heading"><div><span className="eyebrow section-number">01 / THE HOW-TO</span><h2>Four steps.<br/>One very <span className="editorial-serif">you</span> finish.</h2></div><p>No salon chair. No calendar juggling.<br/>Just you, a touchscreen, and your next nail moment.</p></div>
    <div className="steps-grid">
     <article className="step"><div className="step-visual prep-visual"><Hand size={65} strokeWidth={1.1}/><span className="ui-pill"><Check size={13}/> CLEAN + DRY</span><span className="step-index">01</span></div><h3>Prep your nails</h3><p>Start clean and dry. Follow the base-coat instructions on the screen.</p></article>
     <article className="step"><div className="step-visual choose-visual"><div className="tiny-screen"><span>MAKE IT YOURS</span><div className="tiny-designs"><NailImage tile={1} name="Cherry design"/><NailImage tile={5} name="Checkered design"/><NailImage tile={4} name="Floral design"/></div><span className="tiny-screen-footer"><QrCode size={14}/> Or upload your photo</span></div><span className="step-index">02</span></div><h3>Choose or upload</h3><p>Tap a design for each finger, or scan the QR code to upload a photo.</p></article>
     <article className="step"><div className="step-visual print-visual"><img src="/media/process-poster.webp" alt="Nail-printing process from the machine demonstration" width="420" height="300" loading="lazy"/><span className="scan-line"/><span className="step-index">03</span></div><h3>Print, one nail at a time</h3><p>Rest your finger in the bay. Hold still while the machine maps and prints.</p></article>
     <article className="step"><div className="step-visual finish-visual"><NailImage tile={7} name="Glossy cobalt line-art nail inspiration"/><span className="finish-tag"><Sparkles size={16}/> HELLO, NEW NAILS.</span><span className="step-index">04</span></div><h3>Seal, shine, and go</h3><p>Finish with a top coat. Let it set, then get back to your day.</p></article>
    </div><a className="text-link" href="#faqs">First time? Read the quick prep guide</a>
   </section>
   <section id="nail-designs" className="design-section section-space"><div className="section-shell">
    <div className="section-heading"><div><span className="eyebrow section-number">02 / FIND YOUR MOOD</span><h2>Not just nails.<br/><span className="editorial-serif">Your</span> kind of art.</h2></div><div className="gallery-intro"><p>Minimal today. Maximal tomorrow.<br/>Pick a different design for every finger.</p><span className="small-note">Design inspiration · availability varies by machine.</span></div></div>
    <Tabs value={activeCategory} onValueChange={setActiveCategory} className="gallery-tabs"><div className="filter-scroll"><TabsList className="filter-list" aria-label="Filter nail designs">{categories.map(cat=><TabsTrigger key={cat} value={cat} className="filter-button">{cat}</TabsTrigger>)}</TabsList></div>{categories.map(cat=><TabsContent key={cat} value={cat}><div className="design-grid" aria-live="polite">{visibleDesigns.map(design=><button className="design-card" key={design.name} onClick={()=>setSelectedDesign(design)} aria-label={"View "+design.name+" design inspiration"}><div className="design-photo"><NailImage tile={design.tile} name={design.category+" nail-art inspiration"}/><span className="design-view"><Plus size={19}/></span><span className="design-category">{design.category}</span></div><div className="design-card-caption"><h3>{design.name}</h3><span>0{design.tile+1}</span></div></button>)}</div></TabsContent>)}</Tabs>
    <div className="gallery-bottom"><p>Saved something you love? Find your next look on the machine.</p><button className="button button-outline" onClick={()=>{setActiveCategory("All designs");setShowAll(!showAll);}}>{showAll?"Show featured designs":"Browse all designs"}</button></div>
    <div className="custom-band"><div className="custom-mark"><QrCode size={39} strokeWidth={1.4}/></div><div><span className="eyebrow">FROM YOUR CAMERA ROLL TO YOUR NAILS</span><h3>Make it personal. <span className="editorial-serif">Really</span> personal.</h3><p>Your pet. Your favourite photo. Your own little masterpiece. Scan the machine’s QR code and upload an image you have permission to use.</p></div><span className="custom-band-number">100%<small>YOUR IDEA</small></span></div>
   </div></section>
   <section id="machine" className="machine-section section-shell section-space">
    <div className="section-heading"><div><span className="eyebrow section-number">03 / MEET YOUR NEW BEAUTY STOP</span><h2>Small cabinet.<br/>Big <span className="editorial-serif">possibilities.</span></h2></div><p>A self-service nail art studio,<br/>with you in the creative seat.</p></div>
    <div className="machine-layout"><div className="machine-stage"><img src="/images/jolly-machine.webp" alt="Studio visual based on the cabinet in Jolly’s machine preview" width="760" height="850" loading="lazy"/><span className="machine-stage-tag">MEET JOLLY</span><button className="machine-play" onClick={()=>setVideoOpen(true)}><Play size={17} fill="currentColor"/>Watch the printing process</button><span className="machine-stage-caption">Machine preview · appearance may vary</span></div><div className="machine-info">
     <Tabs defaultValue="screen" className="experience-tabs"><TabsList className="experience-tab-list" aria-label="Explore the machine"><TabsTrigger value="screen"><Smartphone/>Choose</TabsTrigger><TabsTrigger value="mapping"><Hand/>Map</TabsTrigger><TabsTrigger value="print"><Sparkles/>Print</TabsTrigger><TabsTrigger value="pay"><CreditCard/>Pay</TabsTrigger></TabsList><TabsContent value="screen"><span className="eyebrow">01 / THE TOUCHSCREEN</span><h3>Your look, at your fingertips.</h3><p>Browse the on-screen catalogue. Give each finger its own design or keep your set coordinated. A QR upload brings your own photo into the mix.</p></TabsContent><TabsContent value="mapping"><span className="eyebrow">02 / NAIL MAPPING</span><h3>Made to fit your nail.</h3><p>The machine reads the shape of your nail before printing. Position one finger at a time and follow the screen’s prompts.</p></TabsContent><TabsContent value="print"><span className="eyebrow">03 / THE PRINTER BAY</span><h3>Watch your idea take shape.</h3><p>Keep your finger still while the design prints directly onto the prepared nail. Then finish with top coat and allow it to set.</p></TabsContent><TabsContent value="pay"><span className="eyebrow">04 / EASY PAYMENT</span><h3>Tap, insert, or pay cash.</h3><p>Pay at the cabinet by cash, card or contactless. Check the on-screen price before you begin. No booking and no app to download.</p></TabsContent></Tabs>
     <div className="surface-list"><span className="eyebrow">PRINT ON THE NAILS YOU HAVE</span><div>{surfaces.map(surface=><span key={surface}><Check size={15}/>{surface}</span>)}</div><p className="small-note">Preparation matters. Follow the instructions for your nail surface.</p></div><div className="payment-icons"><CreditCard size={20}/><span>Cash</span><span>Card</span><span>Contactless</span></div>
    </div></div>
   </section>
   <section id="locations" className="location-section section-space"><div className="section-shell location-layout">
    <div className="location-copy"><span className="eyebrow">04 / NEXT STOP: JOLLY</span><h2>A little closer<br/>to your <span className="editorial-serif">next look.</span></h2><p>We’re bringing self-service nail art to shopping centres, beauty precincts and busy venues across Australia.</p><span className="launch-badge">LAUNCH LOCATIONS COMING SOON</span><form className="location-search" onSubmit={e=>{e.preventDefault();setSearchedLocation(locationInput.trim());}}><label className="sr-only" htmlFor="location-search">Search suburb, city or postcode</label><Search size={20}/><input id="location-search" type="search" placeholder="Suburb, city or postcode" value={locationInput} onChange={e=>setLocationInput(e.target.value)} maxLength={100}/><button type="submit" aria-label="Search for a Jolly machine">Search</button></form><p className="location-note">No confirmed locations yet. Addresses and opening hours will appear here before launch.</p></div>
    <div className="locator-panel"><div className="locator-top"><span><MapPin size={16}/> AUSTRALIA</span><span>{machineLocations.length} confirmed locations</span></div>{matchingLocations.length>0?<div className="location-results">{matchingLocations.map(location=><article className="location-card" key={location.id}><span className="location-availability">{location.availability}</span><h3>{location.centreName}</h3><p>{location.suburb}, {location.city} {location.postcode}</p><dl><div><dt>Find it</dt><dd>{location.level}</dd></div><div><dt>Hours</dt><dd>{location.openingHours}</dd></div></dl><a className="button button-white" href={location.mapUrl} target="_blank" rel="noopener noreferrer">Open map</a></article>)}</div>:<Empty className="location-empty" role="status"><EmptyHeader><EmptyMedia className="location-symbol"><MapPin size={44} strokeWidth={1.2}/></EmptyMedia><EmptyTitle className="location-empty-title">{searchedLocation?"Jolly isn’t here just yet.":"Good things are on the way."}</EmptyTitle><EmptyDescription className="location-empty-description">{searchedLocation?"No confirmed machines for “"+searchedLocation+"”. Our Australian launch locations are coming soon.":"Our first venue is being confirmed. Check back for the centre, level, hours and directions."}</EmptyDescription></EmptyHeader><a href="https://www.instagram.com/ygshopy/" target="_blank" rel="noopener noreferrer" className="button button-white">Follow the launch on Instagram</a></Empty>}<div className="locator-bottom"><span>Centre & level</span><span>Opening hours</span><span>Machine status</span></div></div>
   </div></section>
   <section id="for-venues" className="venue-section section-shell section-space">
    <div className="venue-heading"><span className="eyebrow section-number">05 / LET’S MAKE YOUR VENUE JOLLY</span><h2>A new reason<br/>to <span className="editorial-serif">stop. stay. share.</span></h2><p>Bring a creative beauty experience to your floor. A compact, self-service cabinet gives visitors something new to discover between everything else.</p><a className="button button-blue" href="#venue-enquiry">Bring Jolly to Your Venue</a></div>
    <div className="venue-benefits"><article><span>01</span><div><h3>A reason to visit</h3><p>Add an eye-catching retail experience that invites people to pause and try something new.</p></div><MapPin/></article><article><span>02</span><div><h3>A moment to stay</h3><p>Give visitors an activity to enjoy while they shop, meet friends or explore your venue.</p></div><Clock3/></article><article><span>03</span><div><h3>A look worth sharing</h3><p>Personalised nails make an easy photo moment and a conversation starter.</p></div><Smartphone/></article><article><span>04</span><div><h3>Small space. Simple experience.</h3><p>A compact cabinet, a standard power point and room to stand. Jolly handles servicing, restocking and maintenance.</p></div><Zap/></article></div>
    <div className="venue-types"><span>A NATURAL FIT FOR</span><p>Shopping centres <Asterisk size={16}/> Beauty venues <Asterisk size={16}/> Entertainment spaces <Asterisk size={16}/> Retail landlords</p></div>
    <div id="venue-enquiry" className="enquiry-panel"><div className="enquiry-copy"><span className="eyebrow">THE FIRST STEP IS A CONVERSATION</span><h3>Got the space?<br/>Let’s make it <span className="editorial-serif">Jolly.</span></h3><p>Tell us a little about your venue. We’ll use these details to discuss location suitability, the cabinet and hosting arrangements.</p><a className="enquiry-email" href="mailto:jollynailprinting@gmail.com">jollynailprinting@gmail.com</a><div className="enquiry-footnote"><ShieldCheck size={18}/><span>Your details are used to respond to this enquiry. No marketing subscription.</span></div></div>
     {formStatus==="success"?<div className="form-success" role="status"><span className="success-icon"><Check size={32}/></span><span className="eyebrow">ENQUIRY RECEIVED</span><h3>Let’s make something Jolly.</h3><p>Your venue enquiry has been saved.<br/>Reference: <strong>{reference}</strong></p><p className="small-note">For a direct conversation, email Jolly at the address alongside this form.</p><button className="button button-blue" onClick={()=>{setFormStatus("idle");setConsent(false);setVenueType("");submissionId.current="";}}>Send another enquiry</button></div>:<form className="venue-form" onSubmit={submitVenue}>
      <div className="form-row"><label htmlFor="venue-name">Your name<input id="venue-name" name="name" autoComplete="name" required maxLength={120} placeholder="Full name"/></label><label htmlFor="venue-organisation">Organisation<input id="venue-organisation" name="organisation" autoComplete="organization" required maxLength={180} placeholder="Venue or company name"/></label></div>
      <div className="form-row"><label htmlFor="venue-email">Email<input id="venue-email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@company.com"/></label><label htmlFor="venue-phone">Phone<input id="venue-phone" name="phone" type="tel" autoComplete="tel" required maxLength={35} placeholder="Best contact number"/></label></div>
      <div className="form-row"><div className="form-field"><label id="venue-type-label">Venue type</label><Select value={venueType} onValueChange={setVenueType} name="venueType" required><SelectTrigger aria-labelledby="venue-type-label" className="venue-select"><SelectValue placeholder="Choose your venue type"/></SelectTrigger><SelectContent>{venueTypes.map(type=><SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></div><label htmlFor="venue-city">Suburb / city<input id="venue-city" name="city" autoComplete="address-level2" required maxLength={120} placeholder="Where is your venue?"/></label></div>
      <label htmlFor="venue-message">Tell us about your space<textarea id="venue-message" name="message" rows={3} maxLength={3000} placeholder="Venue details, available space, or anything you’d like to ask."/></label>
      <label className="honeypot" htmlFor="venue-website" aria-hidden="true">Website<input id="venue-website" name="website" tabIndex={-1} autoComplete="off"/></label>
      <div className="consent-row"><Checkbox id="venue-consent" checked={consent} onCheckedChange={value=>setConsent(value===true)} required/><label htmlFor="venue-consent">Jolly can use my details to contact me about hosting a machine.</label></div>
      {formStatus==="error"&&<p className="form-error" role="alert">{formMessage}</p>}<button className="button button-blue form-submit" type="submit" disabled={formStatus==="sending"}>{formStatus==="sending"?"Sending your enquiry…":"Bring Jolly to Your Venue"}</button>
     </form>}
    </div>
   </section>
   <section id="faqs" className="faq-section section-shell section-space"><div className="faq-heading"><span className="eyebrow section-number">06 / GOOD TO KNOW</span><h2>A few details.<br/>Then <span className="editorial-serif">you’re set.</span></h2><p>Your first print, made a little simpler.</p><a className="text-link" href="mailto:jollynailprinting@gmail.com">Still curious? Ask Jolly</a><div className="prep-note"><ShieldCheck size={24}/><p>Clean hands. One finger at a time. Follow the screen. Leave the bay ready for the next person.</p></div></div><Accordion type="single" collapsible className="faq-list">{faqs.map((faq,index)=><AccordionItem value={"faq-"+index} key={faq.q}><AccordionTrigger className="faq-question">{faq.q}</AccordionTrigger><AccordionContent className="faq-answer">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></section>
   <section className="closing-banner"><div className="section-shell"><span className="eyebrow">YOUR NEXT LOOK IS A LITTLE JOLLY.</span><h2>Go on. <span className="editorial-serif">Make your mark.</span></h2><a className="button button-white" href="#locations">Find a Jolly Machine</a></div><Asterisk className="closing-asterisk" strokeWidth={1.3} aria-hidden="true"/></section>
  </main>
  <footer className="footer section-shell"><div className="footer-top"><div><a href="#" className="wordmark footer-logo">jolly<span className="wordmark-dot">.</span><span className="wordmark-caption">NAIL PRINTING</span></a><p>Beauty meets technology.<br/>Self-service nail art, coming to Australia.</p></div><div className="footer-links"><span>EXPLORE</span><a href="#nail-designs">Nail Designs</a><a href="#locations">Locations</a><a href="#faqs">Rules & FAQs</a><a href="#venue-enquiry">Host a Machine</a></div><div className="footer-links"><span>SAY HELLO</span><a href="mailto:jollynailprinting@gmail.com">Email Jolly</a><a href="https://www.instagram.com/ygshopy/" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.tiktok.com/@johnny7777740" target="_blank" rel="noopener noreferrer">TikTok</a></div><div className="footer-statement">A little art.<br/>A lot of <span className="editorial-serif">you.</span><Asterisk size={34}/></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Jolly Nail Printing.</span><span>Nail art printing machines · Australia</span><a href="#faqs">Prep, print & aftercare</a></div></footer>
  <Dialog open={videoOpen} onOpenChange={setVideoOpen}><DialogContent className="video-dialog"><DialogTitle>Meet the Jolly machine</DialogTitle><DialogDescription>Original machine demonstration. Follow the touchscreen instructions when using Jolly.</DialogDescription><video src="/media/machine-demo-01.mp4" controls playsInline preload="metadata" poster="/media/machine-poster.webp"/><p className="small-note">Machine preview supplied on the original Jolly website.</p></DialogContent></Dialog>
  <Dialog open={!!selectedDesign} onOpenChange={open=>{if(!open)setSelectedDesign(null);}}><DialogContent className="design-dialog">{selectedDesign&&<><NailImage tile={selectedDesign.tile} name={selectedDesign.name+" nail design inspiration"} className="modal-nail-image"/><span className="eyebrow">{selectedDesign.category} / DESIGN INSPIRATION</span><DialogTitle className="design-dialog-title">{selectedDesign.name}</DialogTitle><DialogDescription className="design-dialog-description">{selectedDesign.note} These are illustrative design ideas. Browse the actual catalogue and preview your selection on the machine; available designs and finishes can vary.</DialogDescription><a className="button button-blue" href="#locations" onClick={()=>setSelectedDesign(null)}>Find a Jolly Machine</a></>}</DialogContent></Dialog>
 </>;
}
